const attempt = 0, retryer = 2

console.log(attempt)
console.log(retryer)

